apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
