apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-pipeline-demo.fullname" . }}
  labels:
    {{- include "docker-pipeline-demo.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}